export const CATEGORIES: string[] = [
  "Klinik Gigi",
  "Klinik Kesehatan",
  "Klinik Kecantikan",
  "Restoran",
  "Coffee Shop",
  "Salon",
  "Barbershop",
  "Bengkel Motor",
  "Bengkel Mobil",
  "Laundry",
  "Gym",
  "Bimbel",
  "Studio Foto",
  "Kontraktor",
  "Notaris",
  "Rental Mobil",
  "Hotel",
  "Travel",
  "Toko Bangunan",
  "Pet Shop",
];
